Display only VMs that user is supposed to see after manual refresh
oVirt/ovirt-web-ui pull request #1335
Opened 2020-11-30 17:31 UTC by hstastna

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/1330

For the regular fetch (managed through the infinite scroller), `fetchVms` is called in `fetchByPage`, with the `page` set to 1, at least. For the refresh fetch, `fetchVms` is called in `refreshListPage` with no any page set (`undefined`). By `fetchVms`, `getVms` is called and [this condition](https://github.com/oVirt/ovirt-web-ui/blob/master/src/ovirtapi/index.js#L139) is evaluated and it makes the crucial difference in the query which wasn't set correctly. 

**Before:**
![pool_before](https://user-images.githubusercontent.com/13417815/100643044-dc78f880-3339-11eb-817b-671a43838e44.png)

**After:**
![pool_after](https://user-images.githubusercontent.com/13417815/100643051-dedb5280-3339-11eb-94ce-15cb41d13c16.png)

2020-11-30 21:59 UTC, sjd78 approved these changes
LGTM

2020-12-02 16:02 UTC, sgratch requested changes
Most issues on basic original problem mentioned on https://github.com/oVirt/ovirt-web-ui/issues/1330#issuecomment-731200784 are solved now by this fix, but there is still a refresh problem regarding the following (I'm not sure if it's related to latest changes or was there from start after pools redesign):
- User can see all the VM Pool VMs and run all of them exceeding the limit of VM Pool VMs per user.
- The VM Pool card behaves correctly and after running more VM Pool VMs than the user is limited to, the VM Pool card disappears but all of the VM Pool VMs are still present and able to be run.

For reproducing the problem:
- create a pool and run web-ui as a specific user A
- let user A grab a vm out of the pool.
- let user A manually stop that pool's vm via web-ui 

The expected result:
This stopped pool's VM is taken back to the pool and dismissed from user A dashboard and is not permitted to him anymore, as mentioned on stopped vm's warning notification and as should be:
![image](https://user-images.githubusercontent.com/18169498/100895087-d879e180-34c5-11eb-99b7-1c27fce67a69.png)

The actual result:
This stopped vm is back to the pool on backend as it should, but it's still displayed on user A dashboard and is not dismissed, even after using manual refresh (pushing the refresh button). Only hard (F5) refresh dismissed that VM from user A view.

(So user A can still view/start/stop this VM even though it was back to the pool and in case other user takes that VM, user A can still view it and stopped it for him as if it is still owned by him).

2020-12-02 22:05 UTC, hstastna commented
@sgratch I was able to reproduce the problem mentioned above and to debug the code, and I think it is a different problem. I can see `fetchVms` returns the two VMs (which is correct), the query seems to be correct, too, but in `VmCardList` component, there's still data for three VMs in the `vms` prop of the component. I suggest to fix this problem separately as I'm not sure how long would it take to fix it.

2020-12-03 11:40 UTC, sgratch commented
> @sgratch I was able to reproduce the problem mentioned above and to debug the code a little bit, and I think it is a different problem. I can see `fetchVms` returns the two VMs (which is correct), the query seems to be correct, too, but in `VmCardList` React component, there's still data for three VMs in the `vms` prop of the component. I suggest to fix this problem separately as I'm not sure how long would it take to fix it, and as it is a different problem.

Sure, you can open a separate PR for handling this.
This PR looks ok so I'm moving it to QE.

2020-12-06 14:24 UTC, merged