Select The Right "Other OS" operatingSystemId in CreateVmWizard -> BasicSettings according to cluster's cpu architecture.
oVirt/ovirt-web-ui pull request #1349
Opened 2020-12-14 15:19 UTC by bamsalem

Fixes: #1307 .
In CreateVmWizrd -> BasicSettings The operating system drop down includes another options according to selected cluster's CPU architecture (even if it's not visible to users, the IDs are different between architectures), But our default value for "Other OS" is not compatible with all the architectures.

To solve this issue I added new helper function that verifies that every time we sets OperatingSystemId property (not by the user) we check if we selected "Other OS" value that is in the list.
If the selected value is Other OS default values or undefined The function will verify the OperatingSystemId if not it will return the original value.

![image](https://user-images.githubusercontent.com/64131213/102099002-7d82ab80-3e30-11eb-9928-21fe6c4483d5.png)

2020-12-14 15:19 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2020-12-17 20:26 UTC, rszwajko requested changes

2020-12-17 20:26 UTC, rszwajko commented on src/components/CreateVmWizard/helpers.js
> +    const otherOs = osList.find(os => os.value === 'Other OS')
`Other OS` is just English label - check [osinfo-defaults.properties](https://github.com/oVirt/ovirt-engine/blob/2314e3b31e42ff1c96395948af7a9a7f996f56ab/packaging/conf/osinfo-defaults.properties#L38) 
> name is I18N if the one creates a 01-os_${LOCALE}.properties with the co-responding name property

Note also that some OS of type `other` have different English labels i.e.
> os.other_linux.name.value = Linux

I think we should base our logic on unique OS names  and/or IDs.

2020-12-30 14:30 UTC, bamsalem commented
ci add to whitelist

2020-12-30 14:31 UTC, sgratch commented
ci add to whitelist

2020-12-30 14:35 UTC, sgratch commented
ci test please

2020-12-31 19:16 UTC, sgratch commented
@bamsalem please try to change something in the code and push it again for rebuilding the Travis CI.
Other than that it LGTM.

2021-01-03 16:16 UTC, bamsalem commented
> @bamsalem please try to change something in the code and push it again for rebuilding the Travis CI.
> Other than that it LGTM.

@sgratch the checks have passed successfully.

2021-01-03 16:54 UTC, sgratch approved these changes
LGTM

2021-01-27 21:20 UTC, sjd78 approved these changes
LGTM

2021-01-28 10:27 UTC, merged