Create VM Wizard - Add support in creating high performance template based VM
oVirt/ovirt-web-ui pull request #1362
Opened 2021-01-25 18:19 UTC by bamsalem

Before this PR users couldn't create HP (high performance) template based VM via the web UI even if they had the permissions to do so.

This PR adds the ability to create HP template based VM via web UI.

The VM created by using template is not perfect HP VM (for both, web ui and web admin) because there are few parameters that are not included in the template, but VMs created via web ui and web admin by using the same template are identical so we don't want to block it.

Fixes: #1326 

Before:
![image](https://user-images.githubusercontent.com/64131213/105687206-d7cb5d80-5f00-11eb-9619-acf70b2f38db.png)

After:
![image](https://user-images.githubusercontent.com/64131213/105686714-3ba15680-5f00-11eb-99b7-3ad6a6aa290a.png)

2021-01-26 09:16 UTC, rszwajko approved these changes

2021-01-27 13:25 UTC, hstastna requested changes
The changes seem to be ok, except I am not sure about using `optimizedForMap` [here](https://github.com/oVirt/ovirt-web-ui/blob/master/src/components/CreateVmWizard/steps/BasicSettings.js#L189).

_Buggy scenario:_
1. In the CreateVmWizard _Basic settings_ after choosing a cluster, choose a template optimized for high performance.
  => In the _Optimized for_ drop down, the three options are displayed as expected (_Desktop, Server, High Performance_)
2. Select another option in the drop down (_Desktop_ or _Sever_) and don't change anything else

_Actual result:_
The _High Performance_ option is gone, we cannot choose it anymore, we have to select the appropriate template again.
Expected result:
The _High Performance_ option still available, if not changing _Template_ or _Provision Source_.

2021-01-28 17:32 UTC, sgratch reviewed
Please don't forget to verify if this still exists for high performance (based on https://github.com/oVirt/ovirt-web-ui/issues/1237#issue-640542804):
_"For new disks based on a template, the provisioning is based on the "optimized for" field in a way that: If if it's Server or High Performance then provisioning=true (i.e. disks from the template are cloned)
If it's Desktop then provisioning=false (i.e. disks from template are thin provisioned)."_

2021-01-31 16:49 UTC, bamsalem commented
> Please don't forget to verify if this still exists for high performance (based on [#1237 (comment)](https://github.com/oVirt/ovirt-web-ui/issues/1237#issue-640542804)):
> _"For new disks based on a template, the provisioning is based on the "optimized for" field in a way that: If if it's Server or High Performance then provisioning=true (i.e. disks from the template are cloned) If it's Desktop then provisioning=false (i.e. disks from template are thin provisioned)."_

@sgratch 
It works as expected for template "HP_Template2" in default cluster in brq_dev.

2021-02-01 04:25 UTC, sjd78 commented
> > Please don't forget to verify if this still exists for high performance (based on [#1237 (comment)](https://github.com/oVirt/ovirt-web-ui/issues/1237#issue-640542804)):
> > _"For new disks based on a template, the provisioning is based on the "optimized for" field in a way that: If if it's Server or High Performance then provisioning=true (i.e. disks from the template are cloned) If it's Desktop then provisioning=false (i.e. disks from template are thin provisioned)."_
> 
> @sgratch
> It works as expected for template "HP_Template2" in default cluster in brq_dev.

The vm create saga looks at optimized for of 'desktop', so 'server' and 'high performance' are treated the same:

https://github.com/oVirt/ovirt-web-ui/blob/cca163c868cefdaf27736a1b4447ee23c955ef7f/src/sagas/vmChanges.js#L84-L88

2021-02-01 04:25 UTC, sjd78 approved these changes
LGTM

2021-02-01 14:36 UTC, sgratch requested changes
@bamsalem Few comments:
HP=High Performance

- please fix the label displayed on VM details card to use msg.vmType_highPerformance instead of "high_performance" string:
![image](https://user-images.githubusercontent.com/18169498/106467286-18991880-64a5-11eb-8d27-ee6df6a89a73.png)

- I noticed that when creating a new VM based on a HP template and then manually changing the "optimized for" field to "server" or"desktop" then the resulted created VM is not identical. This is since on webadmin we do change few VM properties via the frontend layer which can't be approachable via rest/VM portal as for example "cpu pass-through", "migration mode" etc.
Therefore, I suggest for keeping the consistency to avoid the option of changing the "optimized for" field for HP templates. 
This means that when a HP template is chosen, the optimized for field will display HP value only.

- The resulted HP VM created via web-ui and webadmin are not identical since the vm->Resource Allocation->"Memory Ballooning Enabled" should be disabled for HP VMs as set on the template, but for some reason rest api ignores that and it seems like a regression since it did used to work. This is a backend issue so opened a bug for it: https://bugzilla.redhat.com/show_bug.cgi?id=1923717

2021-02-02 13:22 UTC, bamsalem commented
@sgratch 

> @bamsalem Few comments:
> HP=High Performance
> 
> * please fix the label displayed on VM details card to use msg.vmType_highPerformance instead of "high_performance" string:
>   ![image](https://user-images.githubusercontent.com/18169498/106467286-18991880-64a5-11eb-8d27-ee6df6a89a73.png)

Changed, the key in the `types` object doesn't match to the state HP key, now it works:
![image](https://user-images.githubusercontent.com/64131213/106605491-a2aab500-6569-11eb-9e60-7cbcab41e8c6.png)

> * I noticed that when creating a new VM based on a HP template and then manually changing the "optimized for" field to "server" or"desktop" then the resulted created VM is not identical. This is since on webadmin we do change few VM properties via the frontend layer which can't be approachable via rest/VM portal as for example "cpu pass-through", "migration mode" etc.
>   Therefore, I suggest for keeping the consistency to avoid the option of changing the "optimized for" field for HP templates.
>   This means that when a HP template is chosen, the optimized for field will display HP value only.

Done:
![image](https://user-images.githubusercontent.com/64131213/106605583-bb1acf80-6569-11eb-9df8-330b4935b9b3.png)

> * The resulted HP VM created via web-ui and webadmin are not identical since the vm->Resource Allocation->"Memory Ballooning Enabled" should be disabled for HP VMs as set on the template, but for some reason rest api ignores that and it seems like a regression since it did used to work. This is a backend issue so I opened a bug for it that should be handled by Virt: https://bugzilla.redhat.com/show_bug.cgi?id=1923717.

2021-02-02 18:10 UTC, sgratch commented on src/components/CreateVmWizard/steps/BasicSettings.js
> +    // Appears only for high performance template, to enable creating template based HP VM.
@bamsalem please refer to Hilda's comment above.

2021-02-02 18:23 UTC, sgratch submitted a review, later dismissed
please check Hilda's comment https://github.com/oVirt/ovirt-web-ui/pull/1362#discussion_r565286760 and my inline comment.
Except that, it LGTM.

2021-02-02 18:23 UTC, sgratch commented on src/components/CreateVmWizard/steps/BasicSettings.js
> +    // TODO: remove when web-ui fully supports creating high performance VM
please change the TODO comment position to relate to the whole method and also rephrase to something like "remove when REST API will fully support creating of a High Performance VM type, not based on a template"

2021-02-15 12:03 UTC, sgratch approved these changes
Please note that we still have the following limitation which is planned to be fixed by Virt for  4.4.6:
> The resulted HP VM created via web-ui and webadmin are not identical since the vm->Resource Allocation->"Memory Ballooning Enabled" should be disabled for HP VMs as set on the template, but for some reason rest api ignores that and it seems like a regression since it did used to work. This is a backend issue so I opened a bug for it that should be handled by Virt: https://bugzilla.redhat.com/show_bug.cgi?id=1923717.

Other than that, looks good.

2021-02-15 12:04 UTC, merged

2021-02-26 02:02 UTC, isaranova commented
LGTM