Adding confirmation modal on saving user settings changes
oVirt/ovirt-web-ui pull request #1401
Opened 2021-04-04 14:54 UTC by bamsalem

This PR prompting confirmation before saving changes in user settings.
Before this PR the settings were automatically saved, now before saving the changes will require confirmation.
I added the changed settings to modal's message so the user can see which fields were changed.
Screenshots:
![image](https://user-images.githubusercontent.com/64131213/113512676-621de680-956e-11eb-9027-d37200c2dbdd.png)

![image](https://user-images.githubusercontent.com/64131213/113512714-8b3e7700-956e-11eb-833d-51ce78c71e97.png)

Fixes: #1389.

2021-04-06 09:52 UTC, hstastna reviewed
The code changes LGTM. However, I suggest to change the look to this one:
![confirmation_modal](https://user-images.githubusercontent.com/13417815/113690051-4b40d680-96cb-11eb-9675-8fdf57fca221.png)

Two things:
- I am missing the `?` in the original sentence, in the confirmation modal. The question without the question mark does not feel so good to me

- the string with changed settings was not so clear: same font as the question, items in one line separated by commas - this can be problematic especially when having much more settings in the future

So I tried to put the string with names of the changed settings to the `subContent` prop (instead of `body`) of the `ConfirmationModal` component and added some css (`white-space: pre-wrap;`) to the appropriate element with the subcontent of the component, to achieve new line for each changed setting, together with this change:
```javascript
const mapChangeNamesToString = () => changes.map(name => translatedLabels[name] || name).join('\n')
```
WDYT?

2021-04-06 12:37 UTC, rszwajko commented
Note that we have actually some prototypes.

1. Confirmation with list of VMs impacted - in the original PR #1088  the confirmation dialog was limited to (multi) VM settings. Please check the last screenshot in this comment: https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-543721868
2. Confirmation is case of conflicts - https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-645990615

Looking at those solution I think that bullet pointed list looks  the best

2021-04-06 19:12 UTC, hstastna commented
> Note that we have actually some prototypes.
> 
>     1. Confirmation with list of VMs impacted - in the original PR #1088  the confirmation dialog was limited to (multi) VM settings. Please check the last screenshot in this comment: [#1088 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-543721868)
> 
>     2. Confirmation is case of conflicts - [#1088 (comment)](https://github.com/oVirt/ovirt-web-ui/pull/1088#issuecomment-645990615)
> 
> 
> Looking at those solution I think that bullet pointed list looks the best

Thanks Radek, those prototypes look good to me, too. Just... let's not overcomplicate it. I think this does not have to be the best ;)

2021-04-07 08:07 UTC, rszwajko approved these changes

2021-04-07 08:27 UTC, bamsalem commented
I made few changes:
![image](https://user-images.githubusercontent.com/64131213/113829323-09c52f80-978e-11eb-9207-35beee020576.png)
@hstastna please take a look :)

2021-04-08 09:17 UTC, hstastna requested changes
In my previous review, I suggested some very simple way to achieve the modal info more readable. Now there are more code changes and I'm not sure if it worth regarding the modal look. I still prefer the simpler version. But that's just my preference.

_Settings changes will be made to the following Settings:_ and _Press 'Yes' to confirm these changes._ are unnecessary sentences with no extra information for the user. The user had to read more stuff before they click on some button. I suggest to remove them from the modal. The rest LGTM :)

2021-04-08 09:48 UTC, rszwajko commented
@hstastna 
>  I suggest to remove them from the modal. 
>
OK for me.  Using the list alone is good  enough.

2021-04-12 09:46 UTC, sgratch requested changes
Generally it looks good, few suggestions:
- Any reason for removing the bullets from the bulleted list? 

![image](https://user-images.githubusercontent.com/18169498/114375033-f1d61d00-9b8c-11eb-9f85-25dad1c294ad.png)

- Please reorder the list based on dialog's appearance (language, ssh...)
- This is more related to locale reload issue: 
  if the locale is changed then due to reloading, Notifications fields are not persisted and therefore disabled so it seems strange to notify that they are going to be changed. 
@rszwajko  is this fixed with #1387?

2021-04-12 09:54 UTC, rszwajko commented
> Please reorder the list based on dialog's appearance (language, ssh...)
>

This is not really possible in the current implementation - there is no logical link between the order of properties in the store/state and the order of fields in the UI.  However the problem should be mitigated when we split the screen into subscreens.
 
> This is more related to locale reload issue:
>  if the locale isep changed then due to reloading, Notifications fields are not persisted and therefore disabled so it seems strange to notify that they are going to be changed.
>  @rszwajko  is this fixed with #1387?

Yep.  As for now we don't know which fields are persisted on the server and which are not as framework treats them in a generic way.

2021-04-12 13:19 UTC, bamsalem commented
> * Any reason for removing the bullets from the bulleted list?

No, It's just few changes that weren't staged, I pushed them now :)
 
> * Please reorder the list based on dialog's appearance (language, ssh...)

Before: 
![image](https://user-images.githubusercontent.com/64131213/114397347-45556480-9ba7-11eb-8dc2-4f8626a12b7b.png)

After:
![image](https://user-images.githubusercontent.com/64131213/114398201-31f6c900-9ba8-11eb-8df5-5248fd92edfc.png)

2021-04-12 14:18 UTC, rszwajko requested changes
Can we handle ordering as separate PR? It's not connected with this issue.

Regarding proposed implementation:
1. Maintaining an explicit ordering makes refactorings/enhancements harder. Please infer the order from the existing structures.
2. Global ordering is problematic as more settings are added - it's better to keep the order relative to the section (and then infer order at section level).
3. Aggregate properties into objects instead passing them as separate arrays (and tranlsating back and forth). The main case here are `translatedLabels`, `displayOrder` and `changes`.

2021-04-13 09:10 UTC, bamsalem commented
> Can we handle ordering as separate PR? It's not connected with this issue.

I've removed the order for now.

> Regarding proposed implementation:
> 
> 1. Maintaining an explicit ordering makes refactorings/enhancements harder. Please infer the order from the existing structures.
> 2. Global ordering is problematic as more settings are added - it's better to keep the order relative to the section (and then infer order at section level).
> 3. Aggregate properties into objects instead passing them as separate arrays (and tranlsating back and forth). The main case here are `translatedLabels`, `displayOrder` and `changes`.

I have these changes in my machine let's decide if it should be part of this PR or separate PR.

2021-04-13 09:50 UTC, rszwajko approved these changes

2021-04-13 11:49 UTC, hstastna requested changes
The confirmation modal itself LGTM. But I am getting the error with the changes in this PR (not present on master):
![err](https://user-images.githubusercontent.com/13417815/114547596-e94e1700-9c5e-11eb-806d-1f5771891c7c.png)

2021-04-13 12:20 UTC, sgratch approved these changes

2021-04-13 12:21 UTC, bamsalem commented
> The confirmation modal itself LGTM. But I am getting the error with the changes in this PR (not present on master):
> ![err](https://user-images.githubusercontent.com/13417815/114547596-e94e1700-9c5e-11eb-806d-1f5771891c7c.png)

Fixed by me in #1404 .

2021-04-13 12:21 UTC, sgratch commented
> The confirmation modal itself LGTM. But I am getting the error with the changes in this PR (not present on master):
> ![err](https://user-images.githubusercontent.com/13417815/114547596-e94e1700-9c5e-11eb-806d-1f5771891c7c.png)

@hstastna This error seems due to merged issue https://github.com/oVirt/ovirt-web-ui/issues/1403 (not rebased on top of this PR)

2021-04-13 12:24 UTC, merged

2021-04-13 12:38 UTC, hstastna commented
> > The confirmation modal itself LGTM. But I am getting the error with the changes in this PR (not present on master):
> > ![err](https://user-images.githubusercontent.com/13417815/114547596-e94e1700-9c5e-11eb-806d-1f5771891c7c.png)
> 
> @hstastna This error seems due to merged issue #1403 (not rebased on top of this PR)

I had the freshest code when testing this PR today, and despite the PR #1404 was merged yesterday, I was still getting the error with the changes in this PR. So I had to mention it. But now after merging this PR, the error I've mentioned above is not reproducible anymore. Strange 😄

2021-05-19 20:01 UTC, isaranova commented
LGTM