Update create VM step navigation and disk create checks
oVirt/ovirt-web-ui pull request #1407
Opened 2021-04-20 18:11 UTC by sjd78

Fixes: #1366

Creating a VM from a template with disks defined, and if the disks need to be cloned to a new storage domain, navigation buttons needed to be enabled differently.  Now, once on the storage domain wizard step:

  - The forward button is enabled ONLY when all of the disks are correct and no edit is active.

  - The back button is always enabled, including when:

    - an edit is active

    - no storage domain is available for the template disks

    - disk storage domains must be selected, but have not yet been selected (i.e. edits are active)

When no storage domains are available, and no disks have been defined by the selected template, the `EmptyState` place holder will now show a "cannot create a disk" message.  This message replaces the "Create Disk" button.

---
Active edit:
![VM Portal - Google Chrome_025](https://user-images.githubusercontent.com/3985964/115443951-ebc1eb00-a1e1-11eb-8d4d-8ff5482bc87b.png)

No SD available:
![VM Portal - Google Chrome_026](https://user-images.githubusercontent.com/3985964/115444112-275cb500-a1e2-11eb-8430-a7e35bdb42a5.png)

SD must be selected but have not yet been:
(screen shot coming soon)

Everything OK, forward enabled:
![VM Portal - Google Chrome_027](https://user-images.githubusercontent.com/3985964/115444244-51ae7280-a1e2-11eb-812c-a3764cfbfcd9.png)

2021-04-20 19:45 UTC, sjd78 commented
**NOTE** - A user needs to have `DiskCreator` and `DiskProfileUser` permissions on a storage domain to be able to both create the disk (or clone a disk from another) and to attach the newly created disk to the VM.

2021-04-22 09:16 UTC, sgratch requested changes
It looks now that the "Create VM button" is always disabled:
![image](https://user-images.githubusercontent.com/18169498/115689266-9530ea00-a364-11eb-9fa1-3cc087c23d35.png)

2021-04-22 12:56 UTC, rszwajko commented
@sjd78 
Please check also the following scenario:

1. edit a NIC
2. trigger validation error (i.e. by duplicate name)
3. navigate back to Basic Settings
4. go back to Network Settings

Result: next button is disabled but the edited row is not visible and cannot be corrected.

2021-04-22 13:58 UTC, sjd78 commented
> @sjd78
> Please check also the following scenario:
> 
>     1. edit a NIC
> 
>     2. trigger validation error (i.e. by duplicate name)
> 
>     3. navigate back to Basic Settings
> 
>     4. go back to Network Settings
> 
> 
> Result: next button is disabled but the edited row is not visible and cannot be corrected.

Thanks for finding this one!  I now have the Networking step validate itself on entry in the same way the Storage step does.  Much better!

2021-04-22 15:11 UTC, sgratch approved these changes
LGTM

2021-04-22 15:24 UTC, merged