Support default option in SelectBox
oVirt/ovirt-web-ui pull request #1415
Opened 2021-04-26 12:56 UTC by rszwajko

Mark default options on Account Settings screen for:
1. language
![default_language](https://user-images.githubusercontent.com/64194103/116085705-6043d080-a69f-11eb-91df-481c82b2e1b8.png)
2. refresh interval
![default_referesh_interval](https://user-images.githubusercontent.com/64194103/116085712-6174fd80-a69f-11eb-9e57-3e1e01b55a57.png)

2021-04-26 14:32 UTC, sjd78 requested changes
Just a suggestion on the code style in `SelectBox`

2021-04-26 14:32 UTC, sjd78 commented on src/components/SelectBox.js
> +    const markAsDefault = () => {
I don't think this needs to be a function....

You should be able to do:
```jsx
const MarkAsDefault = <i>{msg.defaultOption()}</i>
```

and then later just do:
```jsx
  {selectedItem && selecteItem.default && <MarkAsDefault />}
```

2021-04-28 10:10 UTC, hstastna approved these changes
LGTM :)

2021-04-28 11:18 UTC, rszwajko commented
@sjd78 
Changes:
1. as suggested moved more responsibility to `MarkAsDefault` component
2. renamed the flag to`isDefault` to prevent name clash with `default` as reserved word

2021-04-30 13:01 UTC, sjd78 approved these changes
LGTM

2021-05-07 13:27 UTC, merged