Add option to reset global settings to default/installation settings
oVirt/ovirt-web-ui pull request #1424
Opened 2021-05-05 11:32 UTC by bamsalem

In this PR I added the option to reset the Global settings to the default/installation settings.
This PR Resolves: #1390 .
The default values (for now) are locale, showNotifications and refreshInterval, in the future we should support also console options.
I added new button on the toolbar left side - "Reset Settings":
![image](https://user-images.githubusercontent.com/64131213/117113741-9403b200-ad93-11eb-860a-0f99d7edd8d6.png).
The button is disabled if the `curruntValues` are equals to the default.
I used the save mechanism so apply the changes and to prevent from the save button activation I added a flag `isReset` that helps us to identify if the current changes are reset or normal saving.

![image](https://user-images.githubusercontent.com/64131213/117113115-b1844c00-ad92-11eb-8b17-cc5cbea62e5f.png)

2021-05-10 10:17 UTC, rszwajko requested changes
1. I would recommend enabling reset only if there is no  pending user changes - otherwise user input will get lost. Perhaps we could then use this info instead of reset flag.
2. confirmation message is missing - we have translated messages for it.

2021-05-10 10:17 UTC, rszwajko commented on src/config.js
> +  defaultLanguage: 'en',
default language is defined in `_/intl` -  we can use it directly (no need to create prop here) i.e check https://github.com/oVirt/ovirt-web-ui/pull/1415

2021-05-10 10:17 UTC, rszwajko commented on src/intl/messages.js
> +  ChangeSuccessfullyReset: 'Settings have been successfully reset',
typo - not camel case

2021-05-12 12:39 UTC, sjd78 approved these changes
LGTM

2021-05-19 16:36 UTC, sgratch reviewed
@bamsalem any reason for avoid resetting the notificationSnoozeDuration back to its init default  value of AppConfiguration.notificationSnoozeDurationInMinutes =10 ?
I think that this option should also be marked as default (a follow up for https://github.com/oVirt/ovirt-web-ui/pull/1415). 
Other than that, looks good.

2021-05-20 12:04 UTC, bamsalem commented
> @bamsalem any reason for avoid resetting the notificationSnoozeDuration back to its init default value of AppConfiguration.notificationSnoozeDurationInMinutes =10 ?
> I think that this option should also be marked as default (a follow up for #1415).
> Other than that, looks good.

Done.

2021-05-20 12:34 UTC, sgratch commented
\

> > @bamsalem any reason for avoid resetting the notificationSnoozeDuration back to its init default value of AppConfiguration.notificationSnoozeDurationInMinutes =10 ?

+1

> > I think that this option should also be marked as default (a follow up for #1415).

Still need to handle this but we can open a separate issue for that.

> > Other than that, looks good.
> 
> Done.

2021-05-20 12:35 UTC, sgratch approved these changes

2021-05-20 12:39 UTC, merged

2021-06-10 22:55 UTC, isaranova commented
LGTM