Load Portuguese or Chinese languages by reading locales from the url
oVirt/ovirt-web-ui pull request #1471
Opened 2021-06-28 22:42 UTC by hstastna

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/1448

Load the chosen language successfully in web-ui after reading query string locale 'pt_BR' or 'zh_CN' from the URL (landing page locales).

**Before:**
 ![before](https://user-images.githubusercontent.com/13417815/123712451-9e619a00-d872-11eb-8258-05917b9392ea.png)

**After:**
![after](https://user-images.githubusercontent.com/13417815/123712456-a1f52100-d872-11eb-959f-81f25ecd5070.png)

2021-06-29 21:17 UTC, sjd78 requested changes
Create a `initialize.test.js` file like `index.test.js` in that same folder and add some unit tests to make sure the function is doing what it is supposed to do.  That'll make it easier to verify your solution will work with other languages.

Tests should cover stuff like:
  - null to null
  - en_US, en_us, en-US, en-us, en to en
  - pt to null
  - pt-PT to null
  - pt_BR, pt_br, pt-BR, pt-br to pt-BR
  - nv to null
  - maybe some variations on the zn-CH locale...

2021-06-30 11:34 UTC, sgratch approved these changes
LGTM (just add unit tests as mentioned by Scott)

2021-07-28 20:56 UTC, sjd78 approved these changes
LGTM

2021-08-02 15:20 UTC, sgratch approved these changes

2021-08-02 15:20 UTC, merged

2021-08-23 17:15 UTC, isaranova commented
LGTM