Boolean transform keep undefined as undefined
oVirt/ovirt-web-ui pull request #1478
Opened 2021-07-10 15:47 UTC by sjd78

Fixes: #1477

For boolean values to be sent to the REST API, the following values are expected:
  - `undefined` stays `undefined` ... no explicit value = no change
  - truthy becomes the string 'true'
  - falsey becomes the string 'false'

This change adds `undefined` handling.  `undefined` needs to stay as `undefined` not get converted to an explicit 'false'.

2021-07-12 08:02 UTC, rszwajko requested changes
1. `undefined` **is** falsy in JS  -  redefinition of this contract might lead to bugs
2. changed signature triggers flow errors

IMHO we should just pass the correct value instead of  relying on (non-standard) behaviour of our REST API (partial update should be PATCH not PUT)

2021-07-12 12:28 UTC, sjd78 commented
>   1. `undefined` **is** falsy in JS  -  redefinition of this contract might lead to bugs
> 

I can't recall a place where an `undefined` for a boolean value was intended to be `false`.  Values over the api need at least 2 options... `undefined` to not send as part of the request, or the actual value to send.  Just so happens that booleans have custom handlers on the rest side that forces to the strings `'true'` and `'false'`.  :shrug: 

>   2. changed signature triggers flow errors
> 
> 
> IMHO we should just pass the correct value instead of relying on (non-standard) behaviour of our REST API (partial update should be PATCH not PUT)

Does our REST API support PATCH over PUT for partial updates?  If it doesn't, it is a moot point.  If it does, then great, let's figure that one out in future.  I'm not looking for perfect here, just working as expected.

2021-07-12 13:31 UTC, rszwajko commented
> I can't recall a place where an `undefined` for a boolean value was intended to be `false`

[convertBool](https://github.com/oVirt/ovirt-web-ui/blob/8d9c8aec9653000acc5b0c135876af4788b50781/src/ovirtapi/transform.js#L56) works this way when parsing the response **from** the server

2021-07-12 17:06 UTC, sjd78 commented
> > I can't recall a place where an `undefined` for a boolean value was intended to be `false`
> 
> [convertBool](https://github.com/oVirt/ovirt-web-ui/blob/8d9c8aec9653000acc5b0c135876af4788b50781/src/ovirtapi/transform.js#L56) works this way when parsing the response **from** the server

True, but we don't have a problem with data coming from the server, just going out to the server.  The `undefined` fix changes the behavior back to what it used to do anyway.  The rest of the app really only sets values on a POST that we want to be changed.  They're all partial updates in some sense. Plus, the model-api has basically everything as being optional, so it still work.

I'll fix the type errors -- void is perfectly acceptable for the relevant attributes according to the schema definitions on the rest entity objects.

2021-07-12 18:05 UTC, sjd78 commented
@rszwajko, @hstastna, @sgratch 

I fixed the type errors by making the attributes optional.  This matches the api schema `maxOccurs="1" minOccurs="0"` defined for those attributes.

I didn't change `toApiBoolean()` itself, but I did:
  - Add a better comment to the function describing its behavior
  - Verify that the other places it is used will not be broken by this change

BTW, did you know you can fetch the RSDL and XSD for the api directly from the api?
  - https://engine.fqdn/ovirt-engine/api?rsdl
  - https://engine.fqdn/ovirt-engine/api?schema

I don't care about POST vs PUT at the moment.

2021-07-13 11:22 UTC, hstastna approved these changes
Interesting change, LGTM 👍🏽

2021-07-21 05:51 UTC, sgratch approved these changes
LGTM

@rszwajko 

> The Flow errors seem fixed. IMHO convertBool and toApiBoolean should be symmetric (following falsy nature of undefined in JS) but I leave it others to decide.

I generally agree but here we just fix it to work as before. Is there any option that the data coming from the server can be set as undefined? Based on api schema it can be either "false" or "true" so there shouldn't be such a problem. 

We can open a follow up PR to fix that if you think it's important.

2021-07-21 05:51 UTC, merged

2021-08-23 18:18 UTC, isaranova commented
LGTM