Handle network errors during page refresh
oVirt/ovirt-web-ui pull request #1536
Opened 2021-11-19 11:13 UTC by rszwajko

Steps to recreate:
1. enter main VM Portal page with VMs/pools
2. disable networking (i.e. using dev tools)
3. trigger manual refresh
Expected result: error notifications are displayed
Actual result: VM Portal crashes

Fixes:
1. error.status == 0  - if network is down the reported status code is
   zero which bypasses some of our checks. Fixed by returning
   the entire error object.
2. temporary network error causes VMs/pools to be removed from
   the dashboard. Fixed by removing only if the server reported 404.
3. use common filtering routine to process VMs and pools retrieved
   during page refresh

2021-12-03 14:54 UTC, sjd78 requested changes
Looks good in general.

2021-12-03 14:54 UTC, sjd78 commented on src/sagas/index.js
> +  } else if (!error && internalPool) {
I prefer the old if structure to the new one ... `if (error) { do errors } else { do success }`.

2021-12-03 14:54 UTC, sjd78 commented on src/sagas/index.js
> +  } else if (!error && internalVm) {
I prefer the old if structure to the new one ... `if (error) { do errors } else { do success }`.

2021-12-06 15:48 UTC, sjd78 approved these changes
LGTM

2021-12-06 15:50 UTC, merged

2022-03-21 15:55 UTC, isaranova commented
Unfortunately, I'm still experiencing this issue. The pool is still visible in the VM portal, but it does not happen always. Once a new pool is created in the Admin portal, it "replaces" the already removed pool in the VM portal.

![Screenshot 2022-03-21 at 16-51-47 VM Portal](https://user-images.githubusercontent.com/39263962/159299834-3fb02949-1453-4296-a4f3-1ff3dbd9c43e.png)
![Screenshot 2022-03-21 at 16-50-25 VM Portal](https://user-images.githubusercontent.com/39263962/159299835-52539899-2058-4c03-8d1d-c0fc36437bdd.png)

2022-03-22 15:21 UTC, rszwajko commented
@isaranova 
> Unfortunately, I'm still experiencing this issue. The pool is still visible in the VM portal, but it does not happen always.
>

Problem can be re-created if there is a single pool in the system and that pool will be deleted.

2022-03-23 13:51 UTC, sgratch commented
> The problem will be tracked under #1573

@isaranova @rszwajko can we close this original issue as done since Radek opened a new one?

2022-03-23 13:56 UTC, isaranova commented
> > The problem will be tracked under #1573
> 
> @isaranova @rszwajko can we close this original issue as done since Radek opened a new one?

Yes