Migrate Account Settings to PF4
oVirt/ovirt-web-ui pull request #1539
Opened 2021-11-26 10:23 UTC by rszwajko

2021-11-26 10:30 UTC, rszwajko commented
### General settings
![account_settings_general_pf4](https://user-images.githubusercontent.com/64194103/143566598-0f8cc77a-fbd8-429b-83d5-892568f9db45.png)
### Refresh rate
![account_settings_refresh_pf4](https://user-images.githubusercontent.com/64194103/143566604-40bc81ea-90e7-4554-bcb1-14b2b88ecbd0.png)
### Notifications
![account_settings_notifications_pf4](https://user-images.githubusercontent.com/64194103/143566606-b0107563-8fe6-40dd-af13-9bdaa63bd1e0.png)
### Console settings
![account_settings_console_top_pf4](https://user-images.githubusercontent.com/64194103/143566613-1f37e524-7a73-476e-9f08-291e7b439ec3.png)
![account_settings_console_bottom_pf4](https://user-images.githubusercontent.com/64194103/143566610-a8427399-1374-4cf5-8c4d-9f9ff0df4e10.png)

2022-01-31 11:23 UTC, ovirt-infra commented
All tests passed

2022-04-06 09:11 UTC, ovirt-infra commented
All tests passed

2022-04-29 15:39 UTC, ovirt-infra commented
All tests passed

2022-05-02 16:42 UTC, ovirt-infra commented
All tests passed

2022-05-27 10:02 UTC, ovirt-infra commented
All tests passed

2022-05-27 19:47 UTC, sjd78 requested changes
The extra `propTypes` on `SettingsBase` look nice.
A handful of nit-picks, but looks real good.

2022-05-27 19:47 UTC, sjd78 commented on src/components/SelectBox.js
> +    </>
nit-pick: I don't think the fragment is necessary

2022-05-27 19:47 UTC, sjd78 commented on src/components/Settings/SettingsBase.js
> +        field.title && (
nit-pick: should be a single line

2022-05-30 09:25 UTC, ovirt-infra commented
All tests passed

2022-05-31 15:08 UTC, sjd78 approved these changes
LGTM

2022-05-31 15:09 UTC, merged