[WIP] VM List PF4
oVirt/ovirt-web-ui pull request #1543
Opened 2021-12-07 15:53 UTC by rszwajko

Includes:
    1. toolbars
    2. tooltips
    3. spinner
    4. masthead icons
    
    Fixes:
    1. use translation independent filters
    2. allow filter multiselection

2021-12-07 16:04 UTC, rszwajko commented
### Overview with filters
![image](https://user-images.githubusercontent.com/64194103/145062295-c5a4d4de-6a92-45ae-999a-fdcf86c12176.png)

### VM Actions on a card
![image](https://user-images.githubusercontent.com/64194103/145062638-b1212c59-736b-4863-8caa-d95a94b899f1.png)

### VM Actions inside toolbar
![image](https://user-images.githubusercontent.com/64194103/145062824-77cf8137-f6ec-4416-88e6-1a0346e01d96.png)
![image](https://user-images.githubusercontent.com/64194103/145062931-0fbc6795-d9fb-4d73-ae48-68bf8c2e2047.png)

### Small screen mode
![image](https://user-images.githubusercontent.com/64194103/145063133-e70e2944-f1c9-4114-b6b5-10c5f652407d.png)
![image](https://user-images.githubusercontent.com/64194103/145063225-33c0b107-d60d-484e-9d06-64ee5e16656c.png)
![image](https://user-images.githubusercontent.com/64194103/145063301-54edbd03-7cc0-4ee7-8433-0a9912477a86.png)

### Account Settings toolbar
![image](https://user-images.githubusercontent.com/64194103/145063488-c9e03cf2-214d-4f19-9433-5cdc49a1b58c.png)

### VM Console toolbar
![image](https://user-images.githubusercontent.com/64194103/145063642-8c3dcfa0-00d2-4a5a-bc7b-f15414eacbcb.png)

2022-01-31 11:26 UTC, ovirt-infra commented
All tests passed

2022-02-21 17:39 UTC, ovirt-infra commented
All tests passed

2022-04-06 09:13 UTC, ovirt-infra commented
All tests passed

2022-04-29 15:57 UTC, ovirt-infra commented
All tests passed

2022-05-02 16:45 UTC, ovirt-infra commented
Some tests failed

2022-05-27 13:47 UTC, ovirt-infra commented
All tests passed

2022-05-27 14:38 UTC, rszwajko commented
@sjd78 @sgratch 
Note that some styling issues has been fixed in https://github.com/oVirt/ovirt-web-ui/pull/1584 i.e. truncating action name on the VM card.

2022-06-03 01:10 UTC, sjd78 requested changes
At first the >4 cards in a row on larger widths was annoying, but it is growing on me.  The spacing between the name/status and action button should match the space between the icon and the name/status.  It looks a bit bigger. (My guess is `.vm-status` style doesn't need a `min-height`).

Your `VmActions` changes are ok with me, I just didn't look very hard.  The original code was a bit of a mess.  Yours looks to work well, so I'm just giving that bit a quick skim. `VmDetailsActions` and `VmDropdownActions` structure is :+1:.

VM List filter toolbar is looking :+1:!

Minimal tweaks suggested.

2022-06-03 01:10 UTC, sjd78 commented on src/components/Toolbar/VmSort.js
> +    isAsc ? <SortAmountDownAltIcon key='altIcon'/> : <SortAmountDownIcon key='icon'/>,
Visuals are just a bit off with this icon.  A bit too small and no left margin from the sort by list.

Should it be clickable to toggle the asc/desc?

2022-06-03 11:37 UTC, ovirt-infra commented
All tests passed

2022-06-03 12:53 UTC, sjd78 commented
L&F issues noted (I'll resolve code comments containing them):

- On card ... The spacing between the name/status and action button should match the space between the icon and the name/status.  It looks a bit bigger. (My guess is `.vm-status` style doesn't need a `min-height`).

- Card Gallery ... There is something off with the gutters. The gallery container itself doesn't seem to have a left and right gutter / margin.  Looks like the scroll-container div has a top and bottom margin padding but needs a left and right to match.

- Toolbar ... `VmSort` font size and asc / desc icon left margin and size are off.  asc/desc icon clickable?

- Toolbar ... the "results of" text font size is smaller than expected

2022-06-06 08:11 UTC, rszwajko commented on src/components/VmConsole/VmConsoleSelector.js
> +  const { msg, locale } = useContext(MsgContext)
1. we need to pass it down to `SelectBox` for sorting
2. this component is expected to be removed once we reach console upgrade PR 1585

2022-06-06 11:17 UTC, ovirt-infra commented
All tests passed

2022-06-06 11:54 UTC, rszwajko commented on src/components/Toolbar/VmsListToolbar.js
> +          </ToolbarItem>
This  looks better after removing PF3 styles in https://github.com/oVirt/ovirt-web-ui/pull/1584

2022-06-06 12:36 UTC, rszwajko commented
/ost

2022-06-06 13:12 UTC, sjd78 approved these changes
LGTM

2022-06-06 13:42 UTC, sjd78 commented
OST fail:

```log
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='col-sm-12']/h5"}
```

2022-06-06 14:05 UTC, rszwajko commented
/ost

2022-06-06 17:00 UTC, rszwajko commented
Forced pushed with minor changes:
```

diff --git a/src/components/Toolbar/VmSort.js b/src/components/Toolbar/VmSort.js
index a4bd3cec..7f0d8cc1 100644
--- a/src/components/Toolbar/VmSort.js
+++ b/src/components/Toolbar/VmSort.js
@@ -61,8 +61,8 @@ const VmSort = ({ sort, msg, onSortChange }) => {
         />
       </ToolbarItem>
       <ToolbarItem>
-        <Button variant='plain' ariaLabel={msg.sortDirection()} onClick={() => onSortChange({ ...sort, isAsc: !isAsc })}>
-          {isAsc ? <SortAmountDownAltIcon/> : <SortAmountDownIcon key='icon'/>}
+        <Button variant='plain' aria-label={msg.sortDirection()} onClick={() => onSortChange({ ...sort, isAsc: !isAsc })}>
+          {isAsc ? <SortAmountDownAltIcon/> : <SortAmountDownIcon/>}
         </Button>
       </ToolbarItem>
     </ToolbarGroup>
diff --git a/src/components/Toolbar/VmsListToolbar.js b/src/components/Toolbar/VmsListToolbar.js
index e448d8e9..ac2989cc 100644
--- a/src/components/Toolbar/VmsListToolbar.js
+++ b/src/components/Toolbar/VmsListToolbar.js
@@ -33,6 +33,12 @@ const VmsListToolbar = ({ match, vms, pools, filters = {}, onClearFilters, msg }
           <VmFilters/>
           <VmSort />
           <ToolbarItem>
+            {
+            /* integration tests (OST) expect VM count under xpath //div[@class='col-sm-12']/h5
+            preserve this path:
+            keep the class 'col-sm-12' as marker class
+            keep the structure <div> followed by <h5> */
+            }
             <div className='col-sm-12'>
               <h5>
                 {

```

2022-06-06 17:00 UTC, ovirt-infra commented
All tests passed

2022-06-06 17:08 UTC, rszwajko commented
/ost

2022-06-06 19:16 UTC, sjd78 commented
Most recent OST fail:
```
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element &lt;a href="#" id="usermenu-logout"&gt;...&lt;/a&gt; is not clickable at point (1451, 100). Other element would receive the click: &lt;div class="pf-c-tooltip__content"&gt;...&lt;/div&gt;
```

2022-06-07 12:23 UTC, merged