Ignore SSO failures when connecting to the console
oVirt/ovirt-web-ui pull request #1550
Opened 2021-12-24 11:44 UTC by rszwajko

In case of unsuccessful SSO logon try to recover by connecting without SSO. The flow is the same as if the user manually ignored the error. This avoids disrupting the user with an error dialog that offers no real choice (beside ignoring the error).
The user will be still informed about unsuccessful logon via notification system (at warning level) so that he will be able to report the problem.

2021-12-24 11:46 UTC, rszwajko commented
### Before
![image](https://user-images.githubusercontent.com/64194103/147350085-c4cfbfb4-a925-4e6d-85f0-728769a6b1ae.png)

### After
![image](https://user-images.githubusercontent.com/64194103/147350128-6497a365-52d5-4170-8a4f-222a31b116d7.png)

2022-01-16 18:46 UTC, sgratch reviewed
@rszwajko 
Removing this  error dialog that leaves no choice for the user seems ok to me, but keeping the SSO logon and this notification warning for all cases seems wrong.
Since SSO and guest agent are deprecated for specific host versions then I'm not sure if this is the correct way to go:

- For hosts that ovirt-guest-agent and therefore SSO are not supported anymore (deprecated) then there is no need to try running SSO logon by default and then displaying a general warning notification of  "SSO failed since guest-agent is not installed..please check if installed...contact if problem continues". The user has nothing to do with that info if this is not supported anymore and it's a misleading one.

- On the other hand, for hosts that still support running ovirt-guest-agent and ovirt-guest-agent is installed ((e.g. rhel <=7) then the SSO logon should run but might fail due to other reasons and therefore the real backend reason for logon failure (result.error) should be displayed as was up til now as part of the event/notification.

How about this suggested solution?: https://github.com/oVirt/ovirt-web-ui/issues/1484#issuecomment-998790111?
Maybe it's better to try running logon only if ovirt-guest-agent is installed and SSO is enabled. If not installed then we don't care if supported or not - we just avoid SSO logon (and can consider displaying an info event for notifying the user that this is not supported since guest-agent is not installed/deprecated). 

If ovirt-guest-agent is installed and SSO is enabled then we can run the same logon use case as today (except of removing this error dialog). In case of an error, a full notification warning with reason details should be displayed.

2022-01-22 00:22 UTC, sjd78 requested changes
Swapping out the dialog for a toast is better UX, so I like how that part looks.

But...in the `openConsole()` saga, the lookup for `hasGuestAgent` needs to be different since it is no longer a fully valid check:
https://github.com/oVirt/ovirt-web-ui/blob/c97d2338c03e7c3d5433ed120f2d05d1cbd88ad8/src/sagas/console/index.js#L170-L190

And `ssoGuestAgent` is parsed from the VM here:
https://github.com/oVirt/ovirt-web-ui/blob/c97d2338c03e7c3d5433ed120f2d05d1cbd88ad8/src/ovirtapi/transform.js#L199

I'd suggest even renaming the `ssoGuestAgent` to something like `attemptSsoOnOpenConsole`.  That way more things can be added to that check and it can still makes semantic sense.

If data about the VM's containing entities (cluster, data center etc) is needed to figure out the value of the new `attemptSsoOnOpenConsole`, then it can be done in the fetch sagas, specifically `transformAndPermitVm()`.  By the time that transform saga runs, all of the hosts, clusters, etc should already be fetched and available via `yield select()`.

2022-01-22 00:22 UTC, sjd78 commented on src/sagas/console/index.js
>    if (hasGuestAgent && !skipSSO) {
The workflow handled by this block needs to be updated to really solve the issue.

2022-01-24 13:27 UTC, rszwajko commented
@sgratch 

> Since SSO and guest agent are deprecated for specific host versions then I'm not sure if this is the correct way to go:
> 
> For hosts that ovirt-guest-agent and therefore SSO are not supported anymore (deprecated) then there is no need to try running SSO logon by default and then displaying a general warning notification of "SSO failed since guest-agent is not installed..please check if installed...contact if problem continues". 
> 

IMHO we should trust the configuration. It seems there is no other reliable way of determining if the OS installed on the VM supports guest agent. 

> The user has nothing to do with that info if this is not supported anymore and it's a misleading one.
>

User should always report such problem to the administrator. 

>  On the other hand, for hosts that still support running ovirt-guest-agent and ovirt-guest-agent is installed ((e.g. rhel <=7) then the SSO logon should run but might fail due to other reasons and therefore the real backend reason for logon failure (result.error) should be displayed as was up til now as part of the event/notification.
> 

+1

> How about this suggested solution?: #1484 (comment)?
>
> Maybe it's better to try running logon only if ovirt-guest-agent is installed and SSO is enabled. If not installed then we don't care if supported or not - we just avoid SSO logon (and can consider displaying an info event for notifying the user that this is not supported since guest-agent is not installed/deprecated).
> 
> If ovirt-guest-agent is installed and SSO is enabled then we can run the same logon use case as today (except of removing this error dialog). In case of an error, a full notification warning with reason details should be displayed.
> 

Regarding the second part of proposed solution:

> > Instead of only checking if vm.sso.method=='guest-agent', also check if guest-agent is installed for that vm (can be done via applications endpoint). So logic can be something like:
if the vm is set with ovirt-guest-agent reported + sshmethod=guest-agent and !skipSSO -> logon
otherwise -> don't logon
>> 

IMHO higher level of confidence is achieved by just trying SSO logon. Consider the possible outcomes of the extra check:
1. the call failed (i.e. due to network issue) - the only recovery action is to just try SSO logon
2. check failed (agent is reported as missing) but VM is marked as having a guest agent. Then we have following possibilities:
   1. configuration is correct and agent is really missing- the admin should investigate why guest agent got lost and re-install it.
   2. configuration is correct and agent is incorrectly reported as missing (i.e. not yet refreshed) - false error will be reported
   2. configuration is incorrect  - the admin should remove the flag manually.
3. check was successful (agent reported as installed) and VM is  configured to support guest agent - then we just perform SSO logon (which may fail due to various reasons including ...missing agent)

2022-01-24 13:40 UTC, rszwajko commented
@sjd78 

> the lookup for hasGuestAgent needs to be different since it is no longer a fully valid check

It still seems the best choice here - please check my response [above](https://github.com/oVirt/ovirt-web-ui/pull/1550#issuecomment-1020100629)

> if data about the VM's containing entities (cluster, data center etc) is needed to figure out the value of the new `attemptSsoOnOpenConsole`, then it can be done in the fetch sagas, specifically `transformAndPermitVm()`. By the time that transform saga runs, all of the hosts, clusters, etc should already be fetched and available via `yield select()`.

As per [this comment](https://github.com/oVirt/ovirt-web-ui/issues/1484#issuecomment-998790111) there is no cluster level setting for this and there are no plans to add it:
> I wouldn't add a backend cluster level configuration for this, because it's not really a cluster-level related feature - and if we drop it in, let's say CL 4.7, then people would just avoid upgrading to that CL

It seems that the only information that a given VM supports guest agent is just a flag on the VM itself. Note also (as per link above):
> the user can still enable this, even if not supported.

2022-01-25 12:52 UTC, ovirt-infra commented
Some tests failed

2022-01-25 12:53 UTC, rszwajko commented
Added notification with server-side SSO error - it's the same message as before but on `warning` level.

![image](https://user-images.githubusercontent.com/64194103/150980404-9e4eb13f-e7fa-49c0-95fc-799e1da86078.png)

2022-01-26 16:44 UTC, sjd78 commented
> @sgratch
> 
> > Since SSO and guest agent are deprecated for specific host versions then I'm not sure if this is the correct way to go:
> > For hosts that ovirt-guest-agent and therefore SSO are not supported anymore (deprecated) then there is no need to try running SSO logon by default and then displaying a general warning notification of "SSO failed since guest-agent is not installed..please check if installed...contact if problem continues".
> 
> IMHO we should trust the configuration. It seems there is no other reliable way of determining if the OS installed on the VM supports guest agent.

That makes perfect sense.  Trying to chase specific guest-agent versions or looking at reported installed software per OS or specific versions of specific packages is purely a loosing proposition.

----

> @sjd78
> 
> > the lookup for hasGuestAgent needs to be different since it is no longer a fully valid check
> 
> It still seems the best choice here - please check my response [above](https://github.com/oVirt/ovirt-web-ui/pull/1550#issuecomment-1020100629)

While the check itself makes sense to keep as is, I still thing renaming the data point in the transformed VM to `attemptSsoOnOpenConsole` makes sense.

> 
> > if data about the VM's containing entities (cluster, data center etc) is needed to figure out the value of the new `attemptSsoOnOpenConsole`, then it can be done in the fetch sagas, specifically `transformAndPermitVm()`. By the time that transform saga runs, all of the hosts, clusters, etc should already be fetched and available via `yield select()`.
> 
> As per [this comment](https://github.com/oVirt/ovirt-web-ui/issues/1484#issuecomment-998790111) there is no cluster level setting for this and there are no plans to add it:
> 
> > I wouldn't add a backend cluster level configuration for this, because it's not really a cluster-level related feature - and if we drop it in, let's say CL 4.7, then people would just avoid upgrading to that CL
> 
> It seems that the only information that a given VM supports guest agent is just a flag on the VM itself. Note also (as per link above):
> 
> > the user can still enable this, even if not supported.

All of that makes sense as well.

----

Net commentary: I understand the minimal nature of the change and with more context that does make sense.  Also, renaming the flag used by the code to something like `attemptSsoOnOpenConsole` still does make sense.  Maybe even a comment in the transform about it?

2022-01-27 13:27 UTC, sjd78 approved these changes
LGTM

2022-01-28 09:51 UTC, ovirt-infra commented
Some tests failed

2022-02-14 19:38 UTC, sgratch commented
@rszwajko @sjd78
 We can assume now that for most VMs, SSO is already deprecated and therefore the solution should be that either the  SSO is skipped for most cases or hidden as much as possible. The best solution is to handle that on backend but since it's more complicated then I suggested  to block that on VM portal side when there is no guest agent installed. This requires an extra query instead of the logon query that is currently running.

Anyway, If you prefer to attempt to logon to the VM every time a console is opened then it's ok as well. But at least hide the SSO attempt as much as possible or raise an informative but still minimal notification warning for the cases it's still supported and failed.

**Current situation**:  the following two notifications are generated almost every time a console is opened and SSO is deprecated:
1. "Single sign on failed. Please check to see if the guest agent is running on your virtual machine. Contact your administrator if the problem continues."
2. Can't open console: [backed  error: Guest agent non responsive]

**My suggestion**:  display only one notification warning instead of two, include  the backend error message but skip the guideline to contact the admin if the problem continues.
Something like: "Single sign on can't run. Please check to see if the agent guest agent is running on your virtual machine [backed  error: Guest agent non responsive]"

2022-02-14 19:40 UTC, sgratch requested changes
Please check my comment for rephrasing the SSO notifications

2022-02-15 10:05 UTC, rszwajko commented
@sgratch 
> We can assume now that for most VMs, SSO is already deprecated and therefore the solution should be that either the SSO is skipped for most cases or hidden as much as possible. 
>

1. AFAIK assumption applies to (some) new VMs using default settings
2. as for 4.5 release, SSO is still supported when creating a VM manually and can be enabled/disabled any time (see below)
![image](https://user-images.githubusercontent.com/64194103/154036216-6ebbc2b7-08c7-4e28-8f1e-590c698692fc.png)


> The best solution is to handle that on backend but since it's more complicated then I suggested to block that on VM portal side > when there is no guest agent installed. This requires an extra query instead of the logon query that is currently running.
> 
> Anyway, If you prefer to attempt to logon to the VM every time a console is opened then it's ok as well.
>

We do logon only if this is requested by the configuration: trusting the configuration seems the most reasonable approach.

> But at least hide the SSO attempt as much as possible or raise an informative but still minimal notification warning for the cases it's still supported and failed.
> 
> **Current situation**: the following two notifications are generated almost every time a console is opened and SSO is deprecated:
> 
>  1. "Single sign on failed. Please check to see if the guest agent is running on your virtual machine. Contact your administrator if the problem continues."
> 
>  2. Can't open console: [backed  error: Guest agent non responsive]
>
> 
> **My suggestion**: display only one notification warning instead of two, include the backend error message but skip the guideline to contact the admin if the problem continues. Something like: "Single sign on can't run. Please check to see if the agent guest agent is running on your virtual machine [backed error: Guest agent non responsive]"
>


1. the (long) message is actually correct: user should contact the administrator in case of SSO errors as only the admin can investigate and fix them (including configuration error).
2.  re-phrasing the message will invalidate the translations - since this is a long and important message I would rather avoid it
3. we could display both messages but this makes the error (shorter message)  less visible.

2022-02-16 10:05 UTC, ovirt-infra commented
All tests passed

2022-02-16 10:05 UTC, rszwajko commented
The notification with the error message:
![image](https://user-images.githubusercontent.com/64194103/154241902-1374eca7-6ef8-4a56-bb87-ba0b73ea5549.png)

2022-02-16 14:06 UTC, rszwajko commented
> > 1. AFAIK assumption applies to (some) new VMs using default settings
> 
> The ovirt-guest-agent and SSO are not supported for VMs running RHEL 8 or later, and for Windows operating systems.. Customers usually upgrade to a newer oVirt verison to enjoy the new RHEL/Virt functionality and therefore need to upgrade their cluster versions to enjoy that. So they will eventually upgrade their clusters to 4.5 and above. Therefore most of their VMs will not support SSO anymore. Only old clusters that were not migrated yet, will still support that for a while until migrated.
>

Correct. This actually confirms my understanding: some new VMs won't support SSO. Old VMs and new VMs with "old" OS should work as before so we cannot "ignore" the flag.
 
> > 2. as for 4.5 release, SSO is still supported when creating a VM manually and can be enabled/disabled any time (see below)
> >    image
> 
> The correct solution was to disable this configuration option on webadmin for those unsupported VMs. I discussed that with Virt team and since it is more complicated to implement, we decided not to do that. So currently, the default of "use guest agent" is enabled even for VMs which we know that won't ever support that. It's a bug.  So the solution was to block that on web-ui only since it's much more easy to do.
>

Note that frontend also cannot distinguish unsupported VMs and ignoring a legal configuration flag would impact valid use cases.

> Therefore, raising a notification with a requirement to "Contact your administrator if the problem continues" is wrong since the problem will continue for those VMs :). We can't ask users to do that on things that we should identify as not supported anymore. It's only text message but it still looks strange to me.
>

As already discussed, incorrectly placed flag is a configuration error. User should report this to the admin and the admin should simply remove the option.

2022-02-16 15:52 UTC, sjd78 requested changes

2022-02-16 15:52 UTC, sjd78 commented on src/intl/messages.js
> +  cantLogonToConsole: 'Single sign on failed. Please check to see if the guest agent is running on your virtual machine. Contact your administrator if the problem continues. Error message: {message}'
```suggestion
  cantLogonToConsole: 'Single sign on failed. Please check to see if the guest agent is running on your virtual machine. Error message: {message}',
```

As per our discussions today, I think changing the error message to the suggested will be sufficient.

2022-02-17 10:56 UTC, ovirt-infra commented
All tests passed

2022-02-17 11:23 UTC, sgratch approved these changes
LGTM

2022-02-17 11:34 UTC, merged

2022-08-04 12:26 UTC, isaranova commented
LGTM