Display notification after successful snapshot restore
oVirt/ovirt-web-ui pull request #1594
Opened 2022-05-26 10:53 UTC by rszwajko

Depends on: #1592 

Restore is synchronous operation so we can interpret completed operation as success.

![image](https://user-images.githubusercontent.com/64194103/170474068-9e0dadbc-624b-4ced-b821-de81e4f36425.png)

2022-05-26 10:54 UTC, ovirt-infra commented
Some tests failed

2022-05-26 10:56 UTC, ovirt-infra commented
Some tests failed

2022-06-03 11:44 UTC, ovirt-infra commented
All tests passed

2022-06-03 11:54 UTC, michalskrivanek commented
/ost

2022-06-06 11:05 UTC, michalskrivanek commented
/ost

2022-06-06 12:11 UTC, ovirt-infra commented
All tests passed

2022-06-07 12:31 UTC, ovirt-infra commented
All tests passed

2022-06-09 07:21 UTC, ovirt-infra commented
All tests passed

2022-06-13 18:00 UTC, sjd78 requested changes

2022-06-14 19:43 UTC, rszwajko commented on src/components/VmDetails/cards/SnapshotsCard/actions.js
> +export function restoreVmSnapshot ({ vmId, vmName, snapshotId, snapshotName }) {
Removed .

2022-06-14 19:54 UTC, ovirt-infra commented
All tests passed

2022-06-14 20:03 UTC, sjd78 commented on src/components/VmDetails/cards/SnapshotsCard/sagas.js
> +    // restore is synchronous operation so we can interpret completed operation as success
> > I see the restore op has async flag on it so looks ok
> 
> Not exactly. The param is there but the backend code ignores it and always perform the operation synchronously -> https://github.com/oVirt/ovirt-engine/blob/6ace5876a5f6bc0f0856968e06516d8966944827/backend/manager/modules/restapi/jaxrs/src/main/java/org/ovirt/engine/api/restapi/resource/BackendSnapshotResource.java#L59

Classic

> 
> > Do you know if the operation is killed if the fetch/request times out?
> 
> No:) but this is an interesting scenario not only in this area :D

:+1:

2022-06-14 20:15 UTC, merged